export const APP_TITLE = "HardwareInfo";

export const STORAGE_KEY = {
  TOKEN: "TOKEN",
  USER: "USER",
};

export const DEVELOPERS = [
  {
    name: "Dima",
    role: "Backend Developer",
    github: "https://github.com/DmytroChup",
    linkedin: "",
    image: "src/assets/images/developers/dima.jpg",
  },
  {
    name: "Yura",
    role: "Backend Developer",
    github: "https://github.com/emeraldDevUA",
    linkedin: "",
    image: "src/assets/images/developers/yura.png",
  },
  {
    name: "Sasha",
    role: "Backend Developer",
    github: "https://github.com/Oleksandr-Kornieiev",
    linkedin: "",
    image: "src/assets/images/developers/sasha.jpg",
  },
  {
    name: "Max",
    role: "Frontend Developer",
    github: "https://github.com/mamamamamaa",
    linkedin: "",
    image: "src/assets/images/developers/mama.jpg",
  },
];

export const rows = [
  {
    id: 1,
    modelName: "GTX 1080",
    itemDescription: "High-end gaming",
    vendor: "Nvidia",
    dieSize: "Medium",
    architecture: "Pascal",
    gpuModel: "GTX 1080",
    tdp: "180W",
    vramType: "GDDR5X",
  },
  {
    id: 2,
    modelName: "RTX 3080",
    itemDescription: "Next-gen gaming",
    vendor: "Nvidia",
    dieSize: "Large",
    architecture: "Ampere",
    gpuModel: "RTX 3080",
    tdp: "320W",
    vramType: "GDDR6X",
  },
  {
    id: 3,
    modelName: "RX 580",
    itemDescription: "Mid-range gaming",
    vendor: "AMD",
    dieSize: "Medium",
    architecture: "Polaris",
    gpuModel: "RX 580",
    tdp: "185W",
    vramType: "GDDR5",
  },
  {
    id: 4,
    modelName: "Vega 64",
    itemDescription: "High-end gaming",
    vendor: "AMD",
    dieSize: "Large",
    architecture: "Vega",
    gpuModel: "Vega 64",
    tdp: "295W",
    vramType: "HBM2",
  },
  {
    id: 5,
    modelName: "RTX 2080 Ti",
    itemDescription: "Ultimate gaming",
    vendor: "Nvidia",
    dieSize: "Large",
    architecture: "Turing",
    gpuModel: "RTX 2080 Ti",
    tdp: "260W",
    vramType: "GDDR6",
  },
  {
    id: 6,
    modelName: "GTX 1070",
    itemDescription: "High-end gaming",
    vendor: "Nvidia",
    dieSize: "Medium",
    architecture: "Pascal",
    gpuModel: "GTX 1070",
    tdp: "150W",
    vramType: "GDDR5",
  },
  {
    id: 7,
    modelName: "RTX 3070",
    itemDescription: "Next-gen gaming",
    vendor: "Nvidia",
    dieSize: "Large",
    architecture: "Ampere",
    gpuModel: "RTX 3070",
    tdp: "220W",
    vramType: "GDDR6",
  },
  {
    id: 8,
    modelName: "RX 570",
    itemDescription: "Mid-range gaming",
    vendor: "AMD",
    dieSize: "Medium",
    architecture: "Polaris",
    gpuModel: "RX 570",
    tdp: "150W",
    vramType: "GDDR5",
  },
  {
    id: 9,
    modelName: "GTX 1660",
    itemDescription: "Mid-range gaming",
    vendor: "Nvidia",
    dieSize: "Medium",
    architecture: "Turing",
    gpuModel: "GTX 1660",
    tdp: "120W",
    vramType: "GDDR5",
  },
  {
    id: 10,
    modelName: "RX 5600 XT",
    itemDescription: "Mid-range gaming",
    vendor: "AMD",
    dieSize: "Medium",
    architecture: "RDNA",
    gpuModel: "RX 5600 XT",
    tdp: "150W",
    vramType: "GDDR6",
  },
  {
    id: 11,
    modelName: "RTX 3060",
    itemDescription: "Next-gen gaming",
    vendor: "Nvidia",
    dieSize: "Medium",
    architecture: "Ampere",
    gpuModel: "RTX 3060",
    tdp: "170W",
    vramType: "GDDR6",
  },
  {
    id: 12,
    modelName: "GTX 1050 Ti",
    itemDescription: "Budget gaming",
    vendor: "Nvidia",
    dieSize: "Small",
    architecture: "Pascal",
    gpuModel: "GTX 1050 Ti",
    tdp: "75W",
    vramType: "GDDR5",
  },
  {
    id: 13,
    modelName: "RX 470",
    itemDescription: "Mid-range gaming",
    vendor: "AMD",
    dieSize: "Medium",
    architecture: "Polaris",
    gpuModel: "RX 470",
    tdp: "120W",
    vramType: "GDDR5",
  },
  {
    id: 14,
    modelName: "RTX 3090",
    itemDescription: "Ultimate gaming",
    vendor: "Nvidia",
    dieSize: "Large",
    architecture: "Ampere",
    gpuModel: "RTX 3090",
    tdp: "350W",
    vramType: "GDDR6X",
  },
  {
    id: 15,
    modelName: "RX 6800 XT",
    itemDescription: "High-end gaming",
    vendor: "AMD",
    dieSize: "Large",
    architecture: "RDNA 2",
    gpuModel: "RX 6800 XT",
    tdp: "300W",
    vramType: "GDDR6",
  },
];

export const columns = [
  { field: "modelName", headerName: "Model Name", width: 130 },
  { field: "vendor", headerName: "Vendor", width: 175, align: "center", headerAlign: "center" },
  { field: "dieSize", headerName: "Die Size", width: 120, align: "center", headerAlign: "center" },
  {
    field: "architecture",
    headerName: "Architecture",
    width: 175,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "gpuModel",
    headerName: "GPU Model",
    width: 175,
    align: "center",
    headerAlign: "center",
  },
  { field: "tdp", headerName: "TDP", width: 100, align: "center", headerAlign: "center" },
  {
    field: "vramType",
    headerName: "VRAM Type",
    width: 175,
    align: "center",
    headerAlign: "center",
  },
] as const;
