import { IconButton, Stack } from "@mui/material";
import EditIcon from "@mui/icons-material/Edit";
import DeleteIcon from "@mui/icons-material/Delete";

export const APP_TITLE = "HardwareInfo";

export const STORAGE_KEY = {
  TOKEN: "TOKEN",
  USER: "USER",
};

export const DEVELOPERS = [
  {
    name: "Dima",
    role: "Backend Developer",
    github: "https://github.com/DmytroChup",
    linkedin: "",
    image: "src/assets/images/developers/dima.jpg",
  },
  {
    name: "Yura",
    role: "Backend Developer",
    github: "https://github.com/emeraldDevUA",
    linkedin: "",
    image: "src/assets/images/developers/yura.png",
  },
  {
    name: "Sasha",
    role: "Backend Developer",
    github: "https://github.com/Oleksandr-Kornieiev",
    linkedin: "",
    image: "src/assets/images/developers/sasha.jpg",
  },
  {
    name: "Max",
    role: "Frontend Developer",
    github: "https://github.com/mamamamamaa",
    linkedin: "",
    image: "src/assets/images/developers/mama.jpg",
  },
];

export const rows = [
  {
    id: 1,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-GTX-1080.jpg",
    modelName: "GTX 1080",
    itemDescription: "High-end gaming",
    vendor: "Nvidia",
    dieSize: "Medium",
    architecture: "Pascal",
    gpuModel: "GTX 1080",
    tdp: "180W",
    vramType: "GDDR5X",
    benchmarkResult: 82,
    vramCapacity: "8GB",
    gpuModelDetails: {
      id: 1,
      dieSize: "Medium",
      architecture: "Pascal",
      gpuVendor: "Nvidia",
      gpuName: "GTX 1080",
      gpuRev: "A1",
      shaderProcessors: 2560,
      rop: 64,
      tmu: 160,
    },
  },
  {
    id: 2,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-RTX-3080.jpg",
    modelName: "RTX 3080",
    itemDescription: "Next-gen gaming",
    vendor: "Nvidia",
    dieSize: "Large",
    architecture: "Ampere",
    gpuModel: "RTX 3080",
    tdp: "320W",
    vramType: "GDDR6X",
    benchmarkResult: 125,
    vramCapacity: "10GB",
    gpuModelDetails: {
      id: 2,
      dieSize: "Large",
      architecture: "Ampere",
      gpuVendor: "Nvidia",
      gpuName: "RTX 3080",
      gpuRev: "A1",
      shaderProcessors: 8704,
      rop: 96,
      tmu: 272,
    },
  },
  {
    id: 3,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/AMD-RX-580.jpg",
    modelName: "RX 580",
    itemDescription: "Mid-range gaming",
    vendor: "AMD",
    dieSize: "Medium",
    architecture: "Polaris",
    gpuModel: "RX 580",
    tdp: "185W",
    vramType: "GDDR5",
    benchmarkResult: 70,
    vramCapacity: "8GB",
    gpuModelDetails: {
      id: 3,
      dieSize: "Medium",
      architecture: "Polaris",
      gpuVendor: "AMD",
      gpuName: "RX 580",
      gpuRev: "A1",
      shaderProcessors: 2304,
      rop: 32,
      tmu: 144,
    },
  },
  {
    id: 4,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/AMD-RX-VEGA-64.jpg",
    modelName: "Vega 64",
    itemDescription: "High-end gaming",
    vendor: "AMD",
    dieSize: "Large",
    architecture: "Vega",
    gpuModel: "Vega 64",
    tdp: "295W",
    vramType: "HBM2",
    benchmarkResult: 80,
    vramCapacity: "8GB",
    gpuModelDetails: {
      id: 4,
      dieSize: "Large",
      architecture: "Vega",
      gpuVendor: "AMD",
      gpuName: "Vega 64",
      gpuRev: "A1",
      shaderProcessors: 4096,
      rop: 64,
      tmu: 256,
    },
  },
  {
    id: 5,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-RTX-2080-Ti.jpg",
    modelName: "RTX 2080 Ti",
    itemDescription: "Ultimate gaming",
    vendor: "Nvidia",
    dieSize: "Large",
    architecture: "Turing",
    gpuModel: "RTX 2080 Ti",
    tdp: "260W",
    vramType: "GDDR6",
    benchmarkResult: 110,
    vramCapacity: "11GB",
    gpuModelDetails: {
      id: 5,
      dieSize: "Large",
      architecture: "Turing",
      gpuVendor: "Nvidia",
      gpuName: "RTX 2080 Ti",
      gpuRev: "A1",
      shaderProcessors: 4352,
      rop: 88,
      tmu: 272,
    },
  },
  {
    id: 6,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-GTX-1070-Ti.jpg",
    modelName: "GTX 1070 Ti",
    itemDescription: "High-end gaming",
    vendor: "Nvidia",
    dieSize: "Medium",
    architecture: "Pascal",
    gpuModel: "GTX 1070 Ti",
    tdp: "150W",
    vramType: "GDDR5",
    benchmarkResult: 75,
    vramCapacity: "8GB",
    gpuModelDetails: {
      id: 6,
      dieSize: "Medium",
      architecture: "Pascal",
      gpuVendor: "Nvidia",
      gpuName: "GTX 1070 Ti",
      gpuRev: "A1",
      shaderProcessors: 2432,
      rop: 64,
      tmu: 152,
    },
  },
  {
    id: 7,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-RTX-3070.jpg",
    modelName: "RTX 3070",
    itemDescription: "Next-gen gaming",
    vendor: "Nvidia",
    dieSize: "Large",
    architecture: "Ampere",
    gpuModel: "RTX 3070",
    tdp: "220W",
    vramType: "GDDR6",
    benchmarkResult: 100,
    vramCapacity: "8GB",
    gpuModelDetails: {
      id: 7,
      dieSize: "Large",
      architecture: "Ampere",
      gpuVendor: "Nvidia",
      gpuName: "RTX 3070",
      gpuRev: "A1",
      shaderProcessors: 5888,
      rop: 96,
      tmu: 184,
    },
  },
  {
    id: 8,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/AMD-RX-570.jpg",
    modelName: "RX 570",
    itemDescription: "Mid-range gaming",
    vendor: "AMD",
    dieSize: "Medium",
    architecture: "Polaris",
    gpuModel: "RX 570",
    tdp: "150W",
    vramType: "GDDR5",
    benchmarkResult: 65,
    vramCapacity: "4GB",
    gpuModelDetails: {
      id: 8,
      dieSize: "Medium",
      architecture: "Polaris",
      gpuVendor: "AMD",
      gpuName: "RX 570",
      gpuRev: "A1",
      shaderProcessors: 2048,
      rop: 32,
      tmu: 128,
    },
  },
  {
    id: 9,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-GTX-1660.jpg",
    modelName: "GTX 1660",
    itemDescription: "Mid-range gaming",
    vendor: "Nvidia",
    dieSize: "Medium",
    architecture: "Turing",
    gpuModel: "GTX 1660",
    tdp: "120W",
    vramType: "GDDR5",
    benchmarkResult: 85,
    vramCapacity: "6GB",
    gpuModelDetails: {
      id: 9,
      dieSize: "Medium",
      architecture: "Turing",
      gpuVendor: "Nvidia",
      gpuName: "GTX 1660",
      gpuRev: "A1",
      shaderProcessors: 1408,
      rop: 48,
      tmu: 88,
    },
  },
  {
    id: 10,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/AMD-RX-5600-XT.jpg",
    modelName: "RX 5600 XT",
    itemDescription: "Mid-range gaming",
    vendor: "AMD",
    dieSize: "Medium",
    architecture: "RDNA",
    gpuModel: "RX 5600 XT",
    tdp: "150W",
    vramType: "GDDR6",
    benchmarkResult: 90,
    vramCapacity: "6GB",
    gpuModelDetails: {
      id: 10,
      dieSize: "Medium",
      architecture: "RDNA",
      gpuVendor: "AMD",
      gpuName: "RX 5600 XT",
      gpuRev: "A1",
      shaderProcessors: 2304,
      rop: 64,
      tmu: 144,
    },
  },
  {
    id: 11,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-RTX-3070.jpg",
    modelName: "RTX 3060",
    itemDescription: "Next-gen gaming",
    vendor: "Nvidia",
    dieSize: "Medium",
    architecture: "Ampere",
    gpuModel: "RTX 3060",
    tdp: "170W",
    vramType: "GDDR6",
    benchmarkResult: 95,
    vramCapacity: "12GB",
    gpuModelDetails: {
      id: 11,
      dieSize: "Medium",
      architecture: "Ampere",
      gpuVendor: "Nvidia",
      gpuName: "RTX 3060",
      gpuRev: "A1",
      shaderProcessors: 3584,
      rop: 48,
      tmu: 112,
    },
  },
  {
    id: 12,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-GTX-1050-Ti.jpg",
    modelName: "GTX 1050 Ti",
    itemDescription: "Budget gaming",
    vendor: "Nvidia",
    dieSize: "Small",
    architecture: "Pascal",
    gpuModel: "GTX 1050 Ti",
    tdp: "75W",
    vramType: "GDDR5",
    benchmarkResult: 50,
    vramCapacity: "4GB",
    gpuModelDetails: {
      id: 12,
      dieSize: "Small",
      architecture: "Pascal",
      gpuVendor: "Nvidia",
      gpuName: "GTX 1050 Ti",
      gpuRev: "A1",
      shaderProcessors: 768,
      rop: 32,
      tmu: 48,
    },
  },
  {
    id: 13,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/AMD-RX-480.jpg",
    modelName: "RX 470",
    itemDescription: "Mid-range gaming",
    vendor: "AMD",
    dieSize: "Medium",
    architecture: "Polaris",
    gpuModel: "RX 470",
    tdp: "120W",
    vramType: "GDDR5",
    benchmarkResult: 60,
    vramCapacity: "4GB",
    gpuModelDetails: {
      id: 13,
      dieSize: "Medium",
      architecture: "Polaris",
      gpuVendor: "AMD",
      gpuName: "RX 470",
      gpuRev: "A1",
      shaderProcessors: 2048,
      rop: 32,
      tmu: 128,
    },
  },
  {
    id: 14,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/Nvidia-RTX-3090.jpg",
    modelName: "RTX 3090",
    itemDescription: "Ultimate gaming",
    vendor: "Nvidia",
    dieSize: "Large",
    architecture: "Ampere",
    gpuModel: "RTX 3090",
    tdp: "350W",
    vramType: "GDDR6X",
    benchmarkResult: 130,
    vramCapacity: "24GB",
    gpuModelDetails: {
      id: 14,
      dieSize: "Large",
      architecture: "Ampere",
      gpuVendor: "Nvidia",
      gpuName: "RTX 3090",
      gpuRev: "A1",
      shaderProcessors: 10496,
      rop: 112,
      tmu: 328,
    },
  },
  {
    id: 15,
    imageUrl: "https://static.userbenchmark.com/resources/static/gpu/AMD-RX-6800.jpg",
    modelName: "RX 6800 XT",
    itemDescription: "High-end gaming",
    vendor: "AMD",
    dieSize: "Large",
    architecture: "RDNA 2",
    gpuModel: "RX 6800 XT",
    tdp: "300W",
    vramType: "GDDR6",
    benchmarkResult: 120,
    vramCapacity: "16GB",
    gpuModelDetails: {
      id: 15,
      dieSize: "Large",
      architecture: "RDNA 2",
      gpuVendor: "AMD",
      gpuName: "RX 6800 XT",
      gpuRev: "A1",
      shaderProcessors: 4608,
      rop: 128,
      tmu: 288,
    },
  },
];

export const rowsOfVendors = [
  { id: 1, vendor: "Nvidia" },
  { id: 2, vendor: "AMD" },
  { id: 3, vendor: "Intel" },
];

export const rowsOfArchitectures = [
  { id: 1, architecture: "Pascal" },
  { id: 2, architecture: "Ampere" },
  { id: 3, architecture: "Polaris" },
  { id: 4, architecture: "Turing" },
  { id: 5, architecture: "RDNA" },
  { id: 6, architecture: "RDNA 2" },
  { id: 7, architecture: "Vega" },
];

export const rowsOfGpuModels = [
  {
    id: 1,
    dieSize: "Medium",
    architecture: "Pascal",
    gpuVendor: "Nvidia",
    gpuName: "GTX 1080",
    gpuRev: "A1",
    shaderProcessors: 2560,
    rop: 64,
    tmu: 160,
  },
  {
    id: 2,
    dieSize: "Large",
    architecture: "Ampere",
    gpuVendor: "Nvidia",
    gpuName: "RTX 3080",
    gpuRev: "A1",
    shaderProcessors: 8704,
    rop: 96,
    tmu: 272,
  },
  {
    id: 3,
    dieSize: "Medium",
    architecture: "Polaris",
    gpuVendor: "AMD",
    gpuName: "RX 580",
    gpuRev: "A1",
    shaderProcessors: 2304,
    rop: 32,
    tmu: 144,
  },
  {
    id: 4,
    dieSize: "Large",
    architecture: "Vega",
    gpuVendor: "AMD",
    gpuName: "Vega 64",
    gpuRev: "A1",
    shaderProcessors: 4096,
    rop: 64,
    tmu: 256,
  },
  {
    id: 5,
    dieSize: "Large",
    architecture: "Turing",
    gpuVendor: "Nvidia",
    gpuName: "RTX 2080 Ti",
    gpuRev: "A1",
    shaderProcessors: 4352,
    rop: 88,
    tmu: 272,
  },
  {
    id: 6,
    dieSize: "Medium",
    architecture: "Pascal",
    gpuVendor: "Nvidia",
    gpuName: "GTX 1070 Ti",
    gpuRev: "A1",
    shaderProcessors: 2432,
    rop: 64,
    tmu: 152,
  },
  {
    id: 7,
    dieSize: "Large",
    architecture: "Ampere",
    gpuVendor: "Nvidia",
    gpuName: "RTX 3070",
    gpuRev: "A1",
    shaderProcessors: 5888,
    rop: 96,
    tmu: 184,
  },
  {
    id: 8,
    dieSize: "Medium",
    architecture: "Polaris",
    gpuVendor: "AMD",
    gpuName: "RX 570",
    gpuRev: "A1",
    shaderProcessors: 2048,
    rop: 32,
    tmu: 128,
  },
  {
    id: 9,
    dieSize: "Medium",
    architecture: "Turing",
    gpuVendor: "Nvidia",
    gpuName: "GTX 1660",
    gpuRev: "A1",
    shaderProcessors: 1408,
    rop: 48,
    tmu: 88,
  },
  {
    id: 10,
    dieSize: "Medium",
    architecture: "RDNA",
    gpuVendor: "AMD",
    gpuName: "RX 5600 XT",
    gpuRev: "A1",
    shaderProcessors: 2304,
    rop: 64,
    tmu: 144,
  },
  {
    id: 11,
    dieSize: "Medium",
    architecture: "Ampere",
    gpuVendor: "Nvidia",
    gpuName: "RTX 3060",
    gpuRev: "A1",
    shaderProcessors: 3584,
    rop: 48,
    tmu: 112,
  },
  {
    id: 12,
    dieSize: "Small",
    architecture: "Pascal",
    gpuVendor: "Nvidia",
    gpuName: "GTX 1050 Ti",
    gpuRev: "A1",
    shaderProcessors: 768,
    rop: 32,
    tmu: 48,
  },
  {
    id: 13,
    dieSize: "Medium",
    architecture: "Polaris",
    gpuVendor: "AMD",
    gpuName: "RX 470",
    gpuRev: "A1",
    shaderProcessors: 2048,
    rop: 32,
    tmu: 128,
  },
  {
    id: 14,
    dieSize: "Large",
    architecture: "Ampere",
    gpuVendor: "Nvidia",
    gpuName: "RTX 3090",
    gpuRev: "A1",
    shaderProcessors: 10496,
    rop: 112,
    tmu: 328,
  },
  {
    id: 15,
    dieSize: "Large",
    architecture: "RDNA 2",
    gpuVendor: "AMD",
    gpuName: "RX 6800 XT",
    gpuRev: "A1",
    shaderProcessors: 4608,
    rop: 128,
    tmu: 288,
  },
];

export const rowsOfTDPs = [
  { id: 1, tdp: "180W" },
  { id: 2, tdp: "320W" },
  { id: 3, tdp: "185W" },
  { id: 4, tdp: "295W" },
  { id: 5, tdp: "260W" },
  { id: 6, tdp: "150W" },
  { id: 7, tdp: "220W" },
  { id: 8, tdp: "120W" },
  { id: 9, tdp: "170W" },
  { id: 10, tdp: "75W" },
];

export const rowsOfVRAMTypes = [
  { id: 1, vramType: "GDDR5X" },
  { id: 2, vramType: "GDDR6X" },
  { id: 3, vramType: "GDDR5" },
  { id: 4, vramType: "HBM2" },
  { id: 5, vramType: "GDDR6" },
  { id: 6, vramType: "GDDR5" },
];

export const columns = [
  { field: "modelName", headerName: "Model Name", width: 130 },
  { field: "vendor", headerName: "Vendor", width: 100, align: "center", headerAlign: "center" },
  { field: "dieSize", headerName: "Die Size", width: 120, align: "center", headerAlign: "center" },
  {
    field: "architecture",
    headerName: "Architecture",
    width: 150,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "gpuModel",
    headerName: "GPU Model",
    width: 150,
    align: "center",
    headerAlign: "center",
  },
  { field: "tdp", headerName: "TDP", width: 100, align: "center", headerAlign: "center" },
  {
    field: "vramType",
    headerName: "VRAM Type",
    width: 140,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "benchmarkResult",
    headerName: "Benchmark Result",
    width: 160,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "vramCapacity",
    headerName: "VRAM Capacity",
    width: 130,
    align: "center",
    headerAlign: "center",
  },
] as const;

export const columnsOfVendors = [
  {
    field: "id",
    headerName: "ID",
    width: 70,
    sortable: true,
    align: "center",
    headerAlign: "center",
  },
  { field: "vendor", headerName: "Vendor", width: 130, sortable: true },
  {
    field: "actions",
    headerName: "Actions",
    width: 150,
    sortable: false,
    renderCell: () => (
      <Stack direction="row" spacing={1}>
        <IconButton color="primary" aria-label="edit" onClick={() => {}}>
          <EditIcon />
        </IconButton>
        <IconButton color="secondary" aria-label="delete" onClick={() => {}}>
          <DeleteIcon />
        </IconButton>
      </Stack>
    ),
  },
] as const;

export const columnsOfArchitectures = [
  {
    field: "id",
    headerName: "ID",
    width: 70,
    sortable: true,
    align: "center",
    headerAlign: "center",
  },
  { field: "architecture", headerName: "Architecture", width: 130, sortable: true },
  {
    field: "actions",
    headerName: "Actions",
    width: 150,
    sortable: false,
    renderCell: () => (
      <Stack direction="row" spacing={1}>
        <IconButton color="primary" aria-label="edit" onClick={() => {}}>
          <EditIcon />
        </IconButton>
        <IconButton color="secondary" aria-label="delete" onClick={() => {}}>
          <DeleteIcon />
        </IconButton>
      </Stack>
    ),
  },
] as const;

export const columnsOfGpuModels = [
  {
    field: "id",
    headerName: "ID",
    type: "number",
    width: 70,
    sortable: true,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "dieSize",
    headerName: "Die Size",
    type: "string",
    width: 80,
  },
  {
    field: "architecture",
    headerName: "Architecture",
    type: "string",
    width: 150,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "gpuVendor",
    headerName: "GPU Vendor",
    type: "string",
    width: 130,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "gpuName",
    headerName: "GPU Name",
    type: "string",
    width: 150,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "gpuRev",
    headerName: "GPU Revision",
    type: "string",
    width: 70,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "shaderProcessors",
    headerName: "Shader Processors",
    type: "number",
    width: 160,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "rop",
    headerName: "ROP",
    type: "number",
    width: 90,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "tmu",
    headerName: "TMU",
    type: "number",
    width: 90,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "actions",
    headerName: "Actions",
    width: 150,
    sortable: false,
    renderCell: () => (
      <Stack direction="row" spacing={1}>
        <IconButton color="primary" aria-label="edit" onClick={() => {}}>
          <EditIcon />
        </IconButton>
        <IconButton color="secondary" aria-label="delete" onClick={() => {}}>
          <DeleteIcon />
        </IconButton>
      </Stack>
    ),
  },
] as const;

export const columnsOfTDPs = [
  {
    field: "id",
    headerName: "ID",
    width: 70,
    sortable: true,
    align: "center",
    headerAlign: "center",
  },
  { field: "tdp", headerName: "TDP", width: 130, sortable: true },
  {
    field: "actions",
    headerName: "Actions",
    width: 150,
    sortable: false,
    renderCell: () => (
      <Stack direction="row" spacing={1}>
        <IconButton color="primary" aria-label="edit" onClick={() => {}}>
          <EditIcon />
        </IconButton>
        <IconButton color="secondary" aria-label="delete" onClick={() => {}}>
          <DeleteIcon />
        </IconButton>
      </Stack>
    ),
  },
] as const;

export const columnsOfVRAMTypes = [
  {
    field: "id",
    headerName: "ID",
    width: 70,
    sortable: true,
    align: "center",
    headerAlign: "center",
  },
  { field: "vramType", headerName: "VRAM Type", width: 130, sortable: true },
  {
    field: "actions",
    headerName: "Actions",
    width: 150,
    sortable: false,
    renderCell: () => (
      <Stack direction="row" spacing={1}>
        <IconButton color="primary" aria-label="edit" onClick={() => {}}>
          <EditIcon />
        </IconButton>
        <IconButton color="secondary" aria-label="delete" onClick={() => {}}>
          <DeleteIcon />
        </IconButton>
      </Stack>
    ),
  },
] as const;
